### ISSUE TITLE
Update NPM, declair dependencies 

### ISSUE THREAD

**Issue by nfriedly** [mikeumus/docpad-plugin-basicauth#7]
Hey, it looks like https://www.npmjs.org/package/docpad-plugin-basicauth is outdated and depends on a global `docpad` object which no longer exists, so it chokes in current versions of DocPad. The code here on github looks better, but I think you might still have some issues with express not being found since it isn't listed in the package.json.

**Comment by mikeumus** [comment]
Express is actually accessed inside DocPad. Yeah I need to republish the updated version. Thanks for the reminder. :wink:

**Comment by nfriedly** [comment]
Cool, and thanks for making it =D

**Comment by mikeumus** [comment]
Hey @nfriedly, I think I've published a good version now to NPM:
- https://www.npmjs.org/package/docpad-plugin-basicauth

Let me know if it works for you and if you have anything else I may help out with. Cheer! :beers:

**Comment by nfriedly** [comment]
So, I just installed the update, but it's still choking - it finds `express` but can't find the `basicAuth` helper. (I think I recall seeing another issue about DocPad's copy of express missing it's middleware, but I can't seem to find it now...)

This is my console output:

```
NDFRIEDL@ADMINIB-EQA3T2O ~/watson-developer-cloud (master)
$ docpad install basicauth
info: Welcome to DocPad v6.69.1 (local installation: c:\Users\IBM_ADMIN\watson-developer-cloud\node_modules\docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: eco, livereload, mongodb, multiplelayouts, raw
info: Environment: development
info: npm install docpad-plugin-basicauth@2 --save
docpad-plugin-basicauth@2.0.2 node_modules\docpad-plugin-basicauth
info: npm install
info: The action completed successfully
info: Shutting down... cya next time!

NDFRIEDL@ADMINIB-EQA3T2O ~/watson-developer-cloud (master)
$ docpad run
info: Welcome to DocPad v6.69.1 (local installation: c:\Users\IBM_ADMIN\watson-developer-cloud\node_modules\docpad)
notice: If everyone who saw this message donated $1/week, maintaining DocPad would become sustainable: http://docpad.org/donate
info: Contribute: http://docpad.org/docs/contribute
info: Plugins: basicauth, eco, livereload, mongodb, multiplelayouts, raw
info: Environment: development
error: Something went wrong with the action
error: An error occured:
TypeError: Object function app(req, res, next){ app.handle(req, res, next); } has no method 'basicAuth'
  at BasicAuthPlugin.serverExtend (c:\Users\IBM_ADMIN\watson-developer-cloud\node_modules\docpad-plugin-basicauth\basicauth.plugin.coffee:21:29)
  at ambi (c:\Users\IBM_ADMIN\watson-developer-cloud\node_modules\docpad\node_modules\ambi\out\lib\ambi.js:57:27)
  at Task.<anonymous> (c:\Users\IBM_ADMIN\watson-developer-cloud\node_modules\docpad\node_modules\event-emitter-grouped\out\lib\event-emitter-grouped.js:4
5:23)
  at ambi (c:\Users\IBM_ADMIN\watson-developer-cloud\node_modules\docpad\node_modules\ambi\out\lib\ambi.js:55:18)
  at fire (c:\Users\IBM_ADMIN\watson-developer-cloud\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:384:27)
  at b (domain.js:183:18)
  at Domain.run (domain.js:123:23)
  at Task.fire (c:\Users\IBM_ADMIN\watson-developer-cloud\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:398:25)
  at Object._onImmediate (c:\Users\IBM_ADMIN\watson-developer-cloud\node_modules\docpad\node_modules\taskgroup\out\lib\taskgroup.js:414:26)
  at processImmediate [as _immediateCallback] (timers.js:345:15)
error: To report the above error, follow the guide at: http://docpad.org/bug-report
info: Shutting down... cya next time!
```

**Comment by nfriedly** [comment]
You're probably working on it right now, but if not, please bump the version and publish to npm when you get a chance ;)
